### ISSUE TITLE
garbage collection

### ISSUE THREAD

**Issue by yegor256** [objectionary/sodg#20]
Right after a call of `Sodg.data()` function, the vertex must be sent to garbage collection, which may or may not delete the vertex. If there are no edges arriving to the vertex -- it may be deleted. If a vertex is deleted, all vertices that are connected to it through edges that depart from it -- must be placed into garbage collection pipeline.

We shouldn't do this in a parallel thread. Everything should be done synchronously.

**Comment by UARTman** [comment]
@yegor256 I think I should probably begin working on this. I'll first implement the prototype that does only what you've outlined and then we'll need to discuss the larger context: how will GC (and `Sodg` itself) be used in the context of the language.

**Comment by UARTman** [comment]
@yegor256 Okay, now that I've started to implements the GC, we need some way to track arriving edges (aka parents). Since we don't currently have it, I'll have to implement it. 

I'll just add a set of `u32`s to each Vertex and update the sets each time we `bind` them. This should work, at least for now, but there will probably be a number of problems when, say, deleting the vertices.

However, at some point we should definitely look at how to store graphs in memory in a more optimal way.

**Comment by UARTman** [comment]
@yegor256 A quick update: I've implemented the basic gc functionality, all that remains are tests. However, I've broken two tests: `prohibits_orphan_edges` and `prohibits_labels_of_broken_format`. They now fail because `Sodg::bind` now errors on v2 not being present, which in turns is caused by the need to update the arrived at vertex for the parent tracking.

**Comment by yegor256** [comment]
@UARTman this seems to be fixed, thanks!
